# Generated by Django 5.0 on 2024-02-29 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_customuser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={},
        ),
    ]
