# Generated by Django 5.0 on 2024-02-29 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_alter_customuser_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
