# Generated by Django 5.0 on 2024-02-29 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_alter_customuser_options'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('authtoken', '0003_tokenproxy'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomUser',
            new_name='User',
        ),
    ]
